# Default Skiko CI
name: CI

on:
  push:
    branches: [ master ]
  # TODO: temporary for faster tests, restore!
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  linux-arm:
    needs: linux
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v3
        name: 'Check out code'

      - uses: actions/setup-java@v3
        name: 'Set up JDK 21'
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'

      - uses: actions/download-artifact@v4
        with:
          name: test-binary-linuxArm64
          path: ./skiko/build/bin/linuxArm64

      - shell: bash
        name: 'Set up Linux build environment'
        run: |
          sudo apt-get update -y
          sudo apt-get install libglu1-mesa-dev libxrandr-dev libdbus-1-dev -y
          sudo apt-get install clang -y
          sudo apt-get remove g++ -y
          sudo Xvfb :0 -screen 0 1280x720x24 +extension GLX &

      - shell: bash
        name: 'Run Linux arm64 tests'
        working-directory: ./skiko
        run: |
          export DISPLAY=:0
          chmod +x ./build/bin/linuxArm64/debugTest/test.kexe
          ./build/bin/linuxArm64/debugTest/test.kexe

      - shell: bash
        name: 'Compile and run AWT tests'
        run: |
          export DISPLAY=:0
          ./gradlew --no-daemon --stacktrace --info -Dskiko.test.onci=true -Dskiko.test.performance.enabled=false :skiko:awtTest
        timeout-minutes: 25

      - shell: bash
        name: 'Publish to Maven Local, check AWT sample'
        run: |
          ./gradlew --no-daemon --stacktrace --info :skiko:publishToMavenLocal
          ./gradlew --no-daemon --stacktrace --info :SkiaAwtSample:installDist

      - uses: actions/upload-artifact@v4
        name: 'Save test results as artifact'
        if: always()
        with:
          name: test-reports-linux-arm
          path: ./skiko/build/reports/tests
          retention-days: 5

